### ISSUE TITLE
Pywal 3.3.0 index out of range error

### ISSUE THREAD

**Issue by Rostiger** [dylanaraps/pywal#528] opened 2020-05-16 14:00 UTC
When I run `wal -i "path-to--valid-img-folder"` I get

```
Traceback (most recent call last):
  File "/home/rostiger/.local/bin/wal", line 11, in <module>
    sys.exit(main())
  File "/home/rostiger/.local/lib/python3.6/site-packages/pywal/__main__.py", line 208, in main
    parse_args(parser)
  File "/home/rostiger/.local/lib/python3.6/site-packages/pywal/__main__.py", line 162, in parse_args
    image_file = image.get(args.i, iterative=args.iterative)
  File "/home/rostiger/.local/lib/python3.6/site-packages/pywal/image.py", line 72, in get
    wal_img = get_random_image(img)
  File "/home/rostiger/.local/lib/python3.6/site-packages/pywal/image.py", line 28, in get_random_image
    images, current_wall = get_image_dir(img_dir)
  File "/home/rostiger/.local/lib/python3.6/site-packages/pywal/image.py", line 17, in get_image_dir
    current_wall = wallpaper.get()
  File "/home/rostiger/.local/lib/python3.6/site-packages/pywal/wallpaper.py", line 154, in get
    return util.read_file(current_wall)[0]
IndexError: list index out of range
```
Any ideas what could cause this?

**Comment by Rostiger** [comment] 2020-05-19 12:32
I was able to solve this by rebooting. My guess is that it was some sort of file system/configuration error that resolved itself upon restarting the system.

**Comment by anoduck** [comment] 2021-11-30 01:38
@Rostiger If the issue was resolved by rebooting your system, this usually entails either pywal itself or an associated library was updated on your system, but was not loaded until reboot. In either case, please close this issue to prevent similar issues from being declared a duplicate of this one.

**Closed** 2021-12-02 05:49 UTC
Labels: bug, can't reproduce
