### ISSUE TITLE
Flatabulous-wal appearing as Raleigh

### ISSUE THREAD

**Issue by JontySR** [dylanaraps/pywal#62] opened 2017-07-28 07:07 UTC
(No Issues page on Flatabulous-wal)

![2017-07-28-090155_1366x768_scrot](https://user-images.githubusercontent.com/25610245/28706301-006bddcc-7374-11e7-92d0-bcccfc0e20f2.png)

As title says. Flatabulous-wal folder as-is from the git repo, in $HOME/.themes/

EDIT: Flatabulous vanilla works perfectly, of course with no colour change.

**Comment by dylanaraps** [comment] 2017-07-28 07:13
Duplicate of https://github.com/dylanaraps/pywal/issues/61.

You need to run `wal` once so that it can generate the color file for GTK2.

**Closed** 2017-07-28 08:36 UTC
