### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by JarrColl** [dylanaraps/pywal#32] opened 2017-07-06 03:54 UTC
Processing /home/jarron/Documents/pywal/pywal
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-4vwlnhlm-build/setup.py", line 13
        DOWNLOAD_URL = f"https://github.com/dylanaraps/pywal/archive/{VERSION}.tar.gz"
                                                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-4vwlnhlm-build/

it happens with both install methods

**Comment by dylanaraps** [comment] 2017-07-06 05:17
You need Python 3.6 or greater to run `pywal`.

Duplicate of #30, #25 and #29.

Please search for closed issues next time.

**Closed by dylanaraps** 2017-07-06 05:17 UTC
Labels: invalid
