### ISSUE TITLE
Transparency doesn'n work with -i flag

### ISSUE THREAD

**Issue by dglha** [dylanaraps/pywal#256] opened 2018-06-06 16:12 UTC
Hi 
After update python-pywal 3.0.1, transpatency doesn't work with -i flag anymore
`wal -i ~/sample.png -a 95`

Os: Archlinux.
Package: urxvt, bspwm, compton, rofi.

**Comment by Danaru87** [comment] 2018-06-07 15:49
Same here, this bug is present since last version (no problem on previous)

**Comment by dylanaraps** [comment] 2018-06-12 21:27
Have you guys tried the latest git master?

**Comment by duongleha** [comment] 2018-06-13 03:15
I tried to unistall and Manual/Git install it but that bug is still there

**Comment by GorrillaRibs** [comment] 2018-06-16 17:44
I've also got this, haven't tried git master yet._

**Comment by GorrillaRibs** [comment] 2018-06-16 19:05
Confirmed, current git master doesn't work but transparency setting with 3.0 works just fine (Manjaro KDE/i3)

**Comment by Jagnat** [comment] 2018-06-18 01:47
I believe my [pull request](https://github.com/dylanaraps/pywal/pull/261) might solve this problem.

**Comment by dylanaraps** [comment] 2018-06-19 00:04
Try the latest master, I just merged Jagnat's PR.

**Comment by deadcombo** [comment] 2018-06-28 08:05
I never experienced this issue, but I'm actually not being able to set transparency if I use a theme from `-f` instead of a colorscheme with `-i`.

**Comment by delightfulagony** [comment] 2018-06-28 10:43
@deadcombo I'd recommend you open a new issue for that since although it's related to this one it's different, but maybe @dylanaraps likes it to be in the same issue, I don't know.

Regarding this issue, I've tested latest master and the issue with the -i flag is solved and transparency works no problem.
***
OS: Archlinux
Packages: URxvt, i3-gaps, compton, rofi
pywal version: master (last commit https://github.com/dylanaraps/pywal/commit/f0480c26a8770c37878b7f04b36058170ea7c22d)

**Comment by deadcombo** [comment] 2018-06-28 11:44
Thank you, I was about to ask you to test it, because judging by your signature we have the same setup. I'll leave it up to you whether warrants a new issue or not.

**Comment by olav35** [comment] 2019-03-01 08:36
I had this issue but i found out that the source of the problem was that my compton opacity-rule for certain programs was set in .xinitrc rather than the compton config. When i changed added the opacity rule in my config rahter then giving it as an option to compton in .xinitrc it worked.

**Closed** 2020-01-23 00:06 UTC
Labels: bug
