### ISSUE TITLE
Ranger/Terminal losing colorscheme after running VIM or accessing the shell from it

### ISSUE THREAD

**Issue by ltgouvea** [dylanaraps/pywal#126] opened 2017-10-18 16:35 UTC
The colorschemes work fine when I first run Ranger and update correctly if I change them from inside ranger by running `wal` with a shorctut, but if I open a file in VIM or press `<S-S>` to reach the shell, the colorscheme is reverted to what seems to be some kind of Xterm default colorscheme. However, on `urxvt` this does not happen.

----
OS: Debian 9 (stretch)
Ranger version: ranger-master 1.9.0b5
Python version: 3.6.3 (default, Oct  3 2017, 21:16:13) [GCC 7.2.0]
pywal version: 0.6.9
Locale: pt_BR.UTF-8
Terminal emulators that are behaviouring like this: `xterm`, `termite`, `terminator`

**Comment by dylanaraps** [comment] 2017-10-19 03:49
This is a possible duplicate of #107 and #109.

This is an issue with `ranger` and there's nothing I can do to fix it sadly.

**Comment by ranisalt** [comment] 2017-10-23 23:26
You can alias `ranger` to `ranger && wal -r` for a quick dirty fix.

**Closed** 2017-12-17 23:12 UTC
Labels: not our bug
