### ISSUE TITLE
Upon opening Terminator with wal in use, ]708;#010203colors: appears in the first line

### ISSUE THREAD

**Issue by Tixle** [dylanaraps/pywal#148] opened 2017-12-29 19:39 UTC
Heya, I know there's a fix somewhere but I can't find it at all from any of the searching and reading I've done. As it states in the title, I use Terminator.

**Comment by dylanaraps** [comment] 2017-12-29 20:03
What's your `wal` version? (`wal` --version`)

I can't reproduce this using the latest version.

**Comment by dylanaraps** [comment] 2017-12-30 20:57
Closing this as it was fixed in `1.0.0`.

**Closed by dylanaraps** 2017-12-30 20:57 UTC

**Comment by Tixle** [comment] 2017-12-31 03:09
I'm still having this issue in 1.0.3-1 in Terminator.

**Comment by dylanaraps** [comment] 2017-12-31 03:23
Try `wal -c` then `wal -i img`. I can't reproduce this at all in `1.0.0`-`1.0.3`.

**Comment by Tixle** [comment] 2017-12-31 03:34
Thanks! That fixed it for me!
