### ISSUE TITLE
Macos broke after using wal command

### ISSUE THREAD

**Issue by AWOLASAP** [dylanaraps/pywal#515] opened 2020-04-18 21:41 UTC
Alright I am going to try to give as much relevant information as I can, but I am in a specific scenario. I install yabai on my mac and also disabled SIP, so this is what I think is the main issue. I used this for about a week with no issues. I then installed pywal with pip3. Upon using the "wal -i" command with an image, my background went black, the dock.app stopped running, workspaces and mission control stopped running. Applications will still run and finder works, but dock.app wont restart, and upon trying to kill any instances of it already running, there are none to be found. I think this is an issue with running wal with SIP disabled, does it edit any system files that could be an issue?
Also let me know if you need more information to diagnose this.

**Comment by robwaz** [comment] 2020-04-18 22:20
The issue is related to the file `Library/Application Support/Dock/desktoppicture.db`.  If you delete this file, macOS will rebuild it and your dock will be restored.


Originally, I thought the issue had something to do with screen rotation, but I cannot replicate it with one external monitor locally regardless of rotation.

How many monitors do you have? 
If possible, can you share your `Library/Application Support/Dock/desktoppicture.db` both before and after running Pywal?

**Comment by AWOLASAP** [comment] 2020-04-18 22:34
Thank you for the information. Not knowing was going wrong, I created a backup (after the incident) and messed around with reinstalling macos, system stuff, etc., but I didn't know what I was doing. I am restoring from the backup and will try to delete this file to see if that fixes the problem. 
I have only my monitor, the one attached to my macbook, but I do use multiple workspaces/desktops (whatever they are called). I will get back to you with the Library/Application Support/Dock/desktoppicture.db files as soon as I can.

**Comment by dawsoneliasen** [comment] 2020-04-19 01:11
> On MacOS Catalina 10.15, and iTerm2 I did wal -i. The colors in iTerm2 changed. Then Dock/Mission Control stopped working. I noticed that there was a problem when my keyboard shortcut to switch desktops stopped working and just sent the key codes to the terminal.
> 
> It wasn't obvious that wal had caused the problem, so I googled "restart Mission Control." Results instructed me to do a killall Dock, but the response was that there were no active Dock processes. I searched in the Activity Monitor for "Dock", nothing came up. Restarted my MacBook a couple times, no change.
> 
> I was able to restore Dock and Mission Control using the accepted answer from this thread. It seems that wal might be creating some sort of corrupted wallpaper file?

**Comment by dawsoneliasen** [comment] 2020-04-19 01:12
@robwaz I have an external monitor that I use with my MacBook. I also use a bunch of the workspaces, not sure if that's related.

**Comment by robwaz** [comment] 2020-04-19 01:24
@dawsoneliasen thanks for the information!

For anyone interested, here's the issue:

When MacOS introduced live wallpapers, the ones that change throughout the day (Mojave?), the way wallpaper information was stored.  Currently, wallpaper data is stored in `~/Library/Application Support/Dock/desktoppicture.db`, a small sqlite database.  As far as I know, this database is undocumented.  I submitted the original changes to Pywal that updated this database.

To date, my original changes still work on my macbook pro, running the latest version of Catalina with one external monitor connected.

In order to fix the issue, I need to identify what is different between my setup and those that experience this issue.  The best thing to determine this is the `desktoppicture.db` both before and after running Pywal.  With that, I can identify what fields in the database need to be changed.

**Comment by AWOLASAP** [comment] 2020-04-19 02:20
Thank you again, that fixed everything. Here is the default .db file that was created after removing the old one, and the .db that was after I ran the wal command. I did customize my dock quite a bit, so I can try to recreate the conditions I was in before I ran wal and get a copy of that .db if you want. (I renamed file extension to txt to upload) 
[Default desktoppicture.txt](https://github.com/dylanaraps/pywal/files/4498235/Default.desktoppicture.txt)
[Post wal desktoppicture.txt](https://github.com/dylanaraps/pywal/files/4498236/Post.wal.desktoppicture.txt)

**Comment by robwaz** [comment] 2020-04-19 05:36
Please uninstall pywal and try using [this fork](https://github.com/robwaz/pywal).  Let me know if the issue persists.

You can install this local fork via the following steps.
1. Uninstall existing pywal (`sudo pip3 uninstall pywal; sudo rm $(which wal)`
2. `git clone https://github.com/robwaz/pywal`
3. `cd pywal`
4. `sudo pip3 install -e ./`

**Comment by robwaz** [comment] 2020-04-20 17:35
@AWOLASAP , @dawsoneliasen ,

Please update on here if the changes in the fork address your issue and I will submit a PR.

**Comment by AWOLASAP** [comment] 2020-04-20 19:02
I followed your instructions and it worked perfectly. My background was changed and the Iterm2 terminal color scheme changed accordingly. Here are the before and after desktoppicture.db files: 
[desktoppicture(after).db.txt](https://github.com/dylanaraps/pywal/files/4505570/desktoppicture.after.db.txt)
[desktoppicture(before).db.txt](https://github.com/dylanaraps/pywal/files/4505572/desktoppicture.before.db.txt)

**Comment by robwaz** [comment] 2020-04-20 19:47
Great!

While looking into the issue, I believe I was able to replicate the issue.  Originally, I cleared the data table, which holds the the wallpaper paths and rewrote it.  I then set all virtual desktops to the new background.

It appears that in some cases, the Dock will read the database before the update is complete, resulting in a failed state (Since the preferences table is referencing non-existent row briefly.).

The current approach appends the new background to the data list and rebuilds the preferences table with the new wallpaper using the stored virtual desktops.  Dock seems to be okay with the preferences table is empty.

It is possible that pywal will not update a virtual desktops if the OS has not yet added an entry to the database for it.  Unfortunately, I cannot add virtual desktops to the database, as I am unsure of how some of the values are being generated or if they are being used elsewhere (UUID in particular).  If other users encounter this scenario, I would recommend manually changing the background for each of your virtual desktops via the MacOS "Desktop & Screen Saver" settings.  This should add a virtual desktop entry to the database.

**Comment by rdavison** [comment] 2020-09-04 07:10
It seems the PR with the fix for this bug has been open for a few months now. I nearly shit my pants earlier when my desktop suddenly went black, finder crashed(?), and the dock stopped working.  Really quite a shocking experience.  However, I found this issue, deleted my desktoppicture.db file, and installed the fork, and it appears my laptop is back to normal. Any reason to withhold merging the PR? https://github.com/dylanaraps/pywal/pull/518

**Comment by SinistreCyborg** [comment] 2020-09-13 17:02
I experienced the issue myself today. Any updates on the PR?

**Closed** 2020-09-13 17:14 UTC

**Comment by nv00** [comment] 2020-11-04 04:40
Just got the same problem, Dock, Mission Control, and some other gestures do not work along with black wallpaper.
I tried at doing the killAll Dock commands in Bash but it said the process didn't exist, then tried deleting com.apple.dock.plist, to no avail it did not restore a thing.
After that I saw the solution is in desktoppicture.db, I went to look for the folder only for it to literally not exist. My presumption is that it was because I deleted the .plist file or the fact that I am on a Big Sur update (11.01 Beta), and it perhaps was relocated. 
I am going to try restoring the .plist file, but I am completely lost on what to do.

**Comment by nv00** [comment] 2020-11-04 04:54
Just experienced the same problem but I am not finding a fix. I first tried deleting the plist file for the dock in preferences folder, then tried using the killAll Dock command, none of it worked. 
I would try messing around with the folder in Application Support but the Dock folder inside of it literally does not exist for me. Not sure if it has to do with me being on Big Sur Beta, or something else I might have done. I have restored the plist file, and I have tried downgrading updates, but the updater wouldn't let me go through with installing. Not quite sure where to go from here.

**Comment by robwaz** [comment] 2020-11-04 04:55
Unfortunately, I cannot provide support for any MacOS Beta.  As you mentioned, the mechanisms involved may have changed.

In the event they haven't, I would recommend running the following command in your terminal to delete the `desktoppicture.db` file. 

```
rm  ~/Library/Application\ Support/Dock/desktoppicture.db
```

**Comment by nv00** [comment] 2020-11-04 05:10
Hey, that worked. Turns out I was looking in the slightly wrong location, it was in the users folder rather than the root. Thanks for the quick response.

**Comment by conxr** [comment] 2021-01-03 09:43
> Unfortunately, I cannot provide support for any MacOS Beta. As you mentioned, the mechanisms involved may have changed.
> 
> In the event they haven't, I would recommend running the following command in your terminal to delete the `desktoppicture.db` file.
> 
> ```
> rm  ~/Library/Application\ Support/Dock/desktoppicture.db
> ```

Thanks for this.

Ran into the same issue as others here and this was the only solution for me. As nv00 also mentioned I could not see that folder in Application Support, as it may have been hidden. Running the command worked instantly.

**Comment by AlejandroE** [comment] 2021-01-26 09:39
This just came in super handy. Thanks you all. 🥇 

Just to report, I had the same problem running:
macOS Big Sur 11.1, yabai, SIP disabled, one external monitor, and several space. 
Deleting the desktoppicture.db fixed it.

**Comment by wantyapps** [comment] 2021-02-07 13:03
This happened to me too...

**Comment by bbamnesia** [comment] 2022-01-20 17:55
> Please uninstall pywal and try using [this fork](https://github.com/robwaz/pywal). Let me know if the issue persists.
> 
> You can install this fork via the following steps.
> 
>     1. Uninstall existing pywal `sudo pip3 uninstall pywal; sudo rm $(which wal)`
> 
>     2. Clone the fork `git clone https://github.com/robwaz/pywal`
> 
>     3. Enter the project directory `cd pywal`
> 
>     4. Install the local project `sudo pip3 install -e ./`

After doing this, pywal no longer works for me.

zsh: command not found: wal

**Comment by bbamnesia** [comment] 2022-01-26 14:08
> 1. udo pip3 uninstall pywal; sudo rm $(which wal)

I get an error of "command not found: wal"

Any idea how I can fix this? On an M1 Mac on Monterey.

**Comment by bbamnesia** [comment] 2022-01-26 14:09
> Please uninstall pywal and try using [this fork](https://github.com/robwaz/pywal). Let me know if the issue persists.
> 
> You can install this fork via the following steps.
> 
>     1. Uninstall existing pywal `sudo pip3 uninstall pywal; sudo rm $(which wal)`
> 
>     2. Clone the fork `git clone https://github.com/robwaz/pywal`
> 
>     3. Enter the project directory `cd pywal`
> 
>     4. Install the local project `sudo pip3 install -e ./`

I get an error of "command not found: wal"

Any idea how to fix this?

**Comment by SamuelBanya** [comment] 2022-02-09 16:54
Still happens on MacOS Monterey 12.1 (21C52) using Pywal Version 3.3.0, aka my dock disappears and I get a black wallpaper.

The only thing that worked to restore the Dock was to remove 'Library/Application Support/Dock/desktoppicture.db' and to wait for my wallpaper to cycle since it cycles every 5 minutes:
`rm  ~/Library/Application\ Support/Dock/desktoppicture.db`

Well... Its safe to say I'm not going to try using this again since this MR was 'merged' into the main branch, yet its still broken:
https://github.com/dylanaraps/pywal/pull/518

**Comment by robwaz** [comment] 2022-02-09 17:55
@SamuelBanya, I just pulled the master branch, and ran pywal on macOS Monterey 12.2 without issue.  I did some testing with cycling wallpapers enabled, but I cannot replicate your issue.

If you wold provide additional information similar to the earlier reported issue, I will look into the issue further.

**Comment by curtbushko** [comment] 2022-02-09 18:51
I think that I have been able to reproduce the issue. I am on Monterey 12.2 also.

When I install by doing 'pip3 install pywal' then that version still has the problem.  Cloning the repo and installing with `pip3 install .` works for me.

I think wherever pip3 gets the version from is broken/not updated?

**Comment by MiraiSubject** [comment] 2023-02-04 11:33
> I think wherever pip3 gets the version from is broken/not updated?

Yeah the package hasn't been updated since 2019, but master is on a commit from 2021, so this project seems to be quite dead. 

You should be able to do `pip3 install git+https://github.com/dylanaraps/pywal.git` to install master as a package directly without going through the step of cloning manually.

**Comment by anwalker293** [comment] 2023-08-07 05:30
HI everyone! I've also recently encountered this issue. Besides just deleting the db, can I ask how everyone is "saving" their environments? (AKA saving in the sense of rescuing) It seems like installing this has really hardcore messed up my environment (just as above, like everyone else is describing)

(Edit: Ah, sorry. Answer = be patient, delete db, and cancel all of those dock instances. Sorry about my post! Hope it helps someone down the line though! :) )

(Second edit: Fork + PR worked like a charm! :) )
