### ISSUE TITLE
invalid syntax with pip install .

### ISSUE THREAD

**Issue by jsheeren2** [dylanaraps/pywal#30] opened 2017-07-03 19:17 UTC
Hi, 

When following the manual install from git (https://github.com/dylanaraps/pywal#manualgit-install ) we get a invalid syntax error

```
$ pip install .
Processing pywal
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-oes2dE-build/setup.py", line 13
        DOWNLOAD_URL = f"https://github.com/dylanaraps/pywal/archive/{VERSION}.tar.gz"
                                                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-oes2dE-build/

```

removing the f in the download url and running the setup again gives another error

```
$ pip install .
Processing pywal
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-m6BX2X-build/setup.py", line 3, in <module>
        import pywal
      File "pywal/__init__.py", line 5, in <module>
        from pywal.settings import __version__  # noqa: F401
      File "pywal/settings.py", line 11, in <module>
        CACHE_DIR = pathlib.Path.home() / ".cache/wal/"
    AttributeError: type object 'Path' has no attribute 'home'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-m6BX2X-build/

```

Running Ubuntu Xenial 16.04

pahtlib version:

```
$ pip list | grep pathlib
pathlib (1.0.1)

```

**Comment by dylanaraps** [comment] 2017-07-03 22:27
You need Python 3.6 or greater to run `pywal`.

Duplicate of #25 and #29.

Please search for closed issues next time.

**Closed by dylanaraps** 2017-07-03 22:27 UTC

**Comment by jsheeren2** [comment] 2017-07-04 10:01
my bad! sorry for distrubing :)
