### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by undying-fish** [dylanaraps/pywal#33] opened 2017-07-06 17:11 UTC
Really liking `wal` and I'm happy to see it move forward like this.

Struggling to install this, however... Errors are as follows:

`pip install pywal`:

```
Collecting pywal
  Using cached pywal-0.3.7.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-s2_a_wt5/pywal/setup.py", line 13
        DOWNLOAD_URL = f"https://github.com/dylanaraps/pywal/archive/{VERSION}.tar.gz"
                                                                                     ^
    SyntaxError: invalid syntax
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-s2_a_wt5/pywal/
```

`pip3 install pywal` returns the same error except the `tmp` directory is `/tmp/pip-build-lcevfskh/pywal/`, as does installing from source. Again in that case the `tmp` directory is different, though I'm not sure it matters.

Running `pywal` without installing it as outlined in CONTRIBUTING.md seems to work okay.

In any case I'm using commit b79c443 .

**Comment by danielx** [comment] 2017-07-06 18:08
Do you have Python 3.6 installed, and is `pip3` pointing to it?

You can check which Python version `pip3` uses with this command:
```bash
$ pip3 -V
```

**Comment by dylanaraps** [comment] 2017-07-07 00:04
You need Python 3.6 or greater to run `pywal`.

Duplicate of #32, #30, #25 and #29.

Please read the docs or search for closed issues next time.

**Closed by dylanaraps** 2017-07-07 00:04 UTC

**Comment by undying-fish** [comment] 2017-07-07 04:14
Bugger, I forgot to check closed issues. Guess I was just that desperate to get going with it.
