### ISSUE TITLE
MacOS iTerm2 improper sequences format

### ISSUE THREAD

**Issue by ConnorChristensen** [dylanaraps/pywal#262] opened 2018-06-20 21:32 UTC
### Problem
The sequences file generated in the cache has some formatting issues that throws a lot of white space and a few random characters on every terminal that I open. My example sequences file looks like this
```
^[]P00f0f0d^[\^[]P1675A4E^[\^[]P28A6236^[\^[]P3917153^[\^[]P4AB8C6C^[\^[]P5748390^[\^[]P6B3B0A9^[\^[]P7e2e8e8^[\^[]P89ea2a2^[\^[]P9675A4E^[\^[]Pa8A6236^[\^[]Pb917153^[\^[]PcAB8C6C^[\^[]Pd748390^[\^[]PeB3B0A9^[\^[]Pfe2e8e8^[\^[]Pge2e8e8^[\^[]Ph0f0f0d^[\^[]Ple2e8e8^[\^[]Ple2e8e8^[\^[]Ple2e8e8^[\^[]Pl0f0f0d^[\^[]Pe80f0f0d^[\^[[s^[[1000H^[[8m^[]Ph0f0f0d^[\^[[u^[]Ple2e8e8^[\
    ^[]6;1;bg;red;brightness;15^G
    ^[]6;1;bg;green;brightness;15^G
    ^[]6;1;bg;blue;brightness;13^G
    

```
I found two issues with this sequence:
1. There is trailing white space
1. One of the color sequences near the end of the first line has one too many characters. It can be identified as begging with ^[]Pe8 and then continuing with the RGB value of the first color value in the sequences.

When running `(cat ~/.cache/wal/sequences &)` the final character on the escape value that is too long is printed (in my case **^[]Pe80f0f0d** prints a **d** on the terminal) and then several lines of white space.

### Fix
1. Remove the extra 8 in **^[]Pe80f0f0d**
1. Remove the extra white space
1. Replace `(cat ~/.cache/wal/sequences &)` with `(cat ~/.cache/wal/sequences | tr -d "\n" &)` to remove the trailing newline character

The fixed sequence file that does not print anything to my screen when loading looks like this
```
^[]P00f0f0d^[\^[]P1675A4E^[\^[]P28A6236^[\^[]P3917153^[\^[]P4AB8C6C^[\^[]P5748390^[\^[]P6B3B0A9^[\^[]P7e2e8e8^[\^[]P89ea2a2^[\^[]P9675A4E^[\^[]Pa8A6236^[\^[]Pb917153^[\^[]PcAB8C6C^[\^[]Pd748390^[\^[]PeB3B0A9^[\^[]Pfe2e8e8^[\^[]Pge2e8e8^[\^[]Ph0f0f0d^[\^[]Ple2e8e8^[\^[]Ple2e8e8^[\^[]Ple2e8e8^[\^[]Pl0f0f0d^[\^[]Pe0f0f0d^[\^[[s^[[1000H^[[8m^[]Ph0f0f0d^[\^[[u^[]Ple2e8e8^[\^[]6;1;bg;red;brightness;15^G^[]6;1;bg;green;brightness;15^G^[]6;1;bg;blue;brightness;13^G
```

### Environment
**macOS High Sierra**: 10.13.5
**MacBook Pro**: 15-inch, Mid 2012
**iTerm2**: Build 3.1.6

**Comment by dylanaraps** [comment] 2018-06-20 21:34
Thanks for the write-up. I'll fix this.

**Comment by dylanaraps** [comment] 2018-06-20 21:47
The extra white-space is fixed.

**Comment by dylanaraps** [comment] 2018-06-20 21:57
I don't have a macOS machine so I can't reproduce nor test the other issues. Do they still occur with the white-space fix?

**Comment by ConnorChristensen** [comment] 2018-06-20 22:10
The white space fix worked.
The extra character is still there though.

**Comment by dylanaraps** [comment] 2018-06-20 22:18
Try the latest commit, it should be fixed now.

**Comment by ConnorChristensen** [comment] 2018-06-20 22:22
Yep! Works perfectly. Thank you for the quick response and fix.

**Comment by dylanaraps** [comment] 2018-06-20 22:23
Thanks for the detailed write-up, that's what helps. :)

**Closed by dylanaraps** 2018-06-20 22:23 UTC
