### ISSUE TITLE
Nested ".config" directory inside ".config/wal/colorschemes"

### ISSUE THREAD

**Issue by khoacao96** [dylanaraps/pywal#236] opened 2018-04-29 06:43 UTC
Is this intentional? When I create `.config/wal/colorschemes` to put custom colorschemes in there, `pywal` seems to create an extra `.config/wal/colorschemes` inside the initial `colorschemes` folder. So now there's another `.config` directory in the same location with my custom colorschemes, inside which is another hierarchy: `.config/wal/colorschemes/`, inside `.config/wal/colorschemes`

Another thing I've just spotted that might be related to this: if there's no `colorschemes` folder inside `.config/wal`, running `wal --theme` will output errors:

`Traceback (most recent call last):
  File "/usr/bin/wal", line 11, in <module>
    load_entry_point('pywal==2.0.5', 'console_scripts', 'wal')()
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 187, in main
    parse_args_exit(parser)
  File "/usr/lib/python3.6/site-packages/pywal/__main__.py", line 120, in parse_args_exit
    for theme in theme.list_themes()]
  File "/usr/lib/python3.6/site-packages/pywal/theme.py", line 15, in list_themes
    themes = [*os.scandir(os.path.join(CONF_DIR, "colorschemes")),
FileNotFoundError: [Errno 2] No such file or directory: '/home/xxxxxx/.config/wal/colorschemes'`

`pywal` could have just created the `colorschemes` folder if it didn't exist, right?

To sumup, it seems like: if the `colorschemes` folder doesn't exist inside `.config/wal`, `pywal` will throw errors without doing anything; and if the `colorschemes` folder is there, `pywal` will create another folder of the same hierarchy: `.config/wal/colorschemes` inside it.

EDIT: the nested `.config` folder will appear after you apply the custom colorscheme with: `wal --theme .config/wal/colorschemes/<scheme_name>`

**Comment by dylanaraps** [comment] 2018-04-29 09:10
Thanks for finding these. 👍

**Comment by dylanaraps** [comment] 2018-04-29 09:42
I've fixed the issue of the dirs not being created early enough (*the --theme error*). I can't reproduce the nested directories bug though. Can you delete the nested structure and try the latest git master to see if the issue still occurs? It may have been fixed with the first fix.

**Comment by khoacao96** [comment] 2018-04-29 09:53
@dylanaraps Just tested the git version. The --theme error is indeed fixed, but the nested directory bug is still there. I managed to find an easier way to reproduce it. Just run this **exact** command (assuming that there's no file called `test` in the `colorschemes` folder):

`wal --theme .config/wal/colorschemes/test`

Now, when you go inside the `colorschemes` folder, there will be a hidden folder called `.config` with the same hierarchy that you ran the previous command. Well, at least that's what happened on my machine.

**Comment by dylanaraps** [comment] 2018-04-29 10:02
Try the latest commit.

**Comment by khoacao96** [comment] 2018-04-29 10:06
@dylanaraps Yep the issue is fixed. Thank you!

**Comment by dylanaraps** [comment] 2018-04-29 10:07
No problem! Thanks for the detailed bug report. I'll make a new release either tonight or tomorrow. :)

**Closed** 2018-04-29 10:06 UTC
