### ISSUE TITLE
-b & -a ignored in st

### ISSUE THREAD

**Issue by tomaskallup** [dylanaraps/pywal#446] opened 2019-08-27 10:03 UTC
When i run `wal -i ...` in my __st__, it changes background to color of foreground (rendering text invisible), i tried `-b '#000000'` and `-a 0.8` (i use this transparency in st) and it ruins all my running st instances. I have a custom Xresources template and load that when st starts, so restarting st fixes this but it feels weird, that background gets set incorrectly during wal generation yet it's correct in the Xresources.

My Xresources template:
```
! X colors.
! Generated by 'wal'
*background:   {background}
*foreground:   {foreground}
*cursorColor:  #ffffff

! Colors 0-15.
*color0:  {color0}
*color1:  {color1}
*color2:  {color2}
*color3:  {color3}
*color4:  {color4}
*color5:  {color5}
*color6:  {color6}
*color7:  {color7}
*color8:  {color8}
*color9:  {color9}
*color10:  {color10}
*color11:  {color11}
*color12:  {color12}
*color13:  {color13}
*color14:  {color14}
*color15:  {color15}

! Black color that will not be affected by bold highlighting.
*color66:  {color0}

*alpha:  0.8
```

Gif which is probably better than my explanation:
![pywal-background](https://user-images.githubusercontent.com/26621166/63762076-84478100-c8c2-11e9-969e-2d5a4b57da4d.gif)

**Comment by dithpri** [comment] 2019-08-29 01:02
This is probably a duplicate of #445

**Comment by dylanaraps** [comment] 2019-08-29 05:45
`-a` is a URxvt only feature. Does `-b` work without `-a`?

**Comment by tomaskallup** [comment] 2019-08-29 13:25
@dylanaraps with only `-b` it's still the same, it breaks my transparency and uses color generated from image (in the example its grayish color). I would love an option to just skip setting background

**Comment by tomaskallup** [comment] 2019-09-23 09:19
@dylanaraps Is there anything I can do? My current workaround is using `-st` switch and restarting all my running terminals, which is not ideal.

**Comment by dylanaraps** [comment] 2020-01-22 23:54
If it doesn't work it means that `st` has no support for the sequence.

**Closed by dylanaraps** 2020-01-22 23:54 UTC

**Comment by tomaskallup** [comment] 2020-01-23 08:30
@dylanaraps Well I would still like a solution, which doesn't involve restarting my terminal, because i the current state, `pywal` makes all my terminals unreadable (sets same background color & white color) and I need to restart them.

I would be nice to have a switch which would disable outputting background & alpha color sequences.
