### ISSUE TITLE
rofi color don't change

### ISSUE THREAD

**Issue by FreedomSka** [dylanaraps/pywal#150] opened 2017-12-30 15:06 UTC
I have i3-gaps, I've runned ```wal -i <path to image>``` and the color changed on everything except for **rofi**

**my config.rasi [rofi config color scheme]**

```
/* global settings and color variables */
* {
   maincolor:        #ed8712;
   highlight:        bold #ed8712;
   urgentcolor:      #e53714;

   fgwhite:          #cfcfcf;
   blackdarkest:     #1d1d1d;
   blackwidget:      #262626;
   blackentry:       #292929;
   blackselect:      #303030;
   darkgray:         #848484;
   scrollbarcolor:   #505050;
   font: "Hack 8";
   background-color: @blackdarkest;
}
```

i run rofi via i3 config using
```
bindsym $mod+d exec rofi -show run -separator-style solid -font "Hack 8"
bindsym $mod+shift+d exec rofi -show window -separator-style solid -font "Hack 8"
```

**my .Xresource**

```
! freetype2-infinality
Xft.autohint: 0
Xft.lcdfilter:  lcddefault
Xft.hintstyle:  hintslight
Xft.hinting: 1
Xft.antialias: 1
Xft.rgba: rgb

! special
*.foreground:   #a8a19f
*.background:   #1b1918
*.cursorColor:  #a8a19f

! black
*.color0:       #1b1918
*.color8:       #766e6b

! red
*.color1:       #f22c40
*.color9:       #f22c40

! green
*.color2:       #5ab738
*.color10:      #5ab738

! yellow
*.color3:       #d5911a
*.color11:      #d5911a

! blue
*.color4:       #407ee7
*.color12:      #407ee7

! magenta
*.color5:       #6666ea
*.color13:      #6666ea

! cyan
*.color6:       #00ad9c
*.color14:      #00ad9c

! white
*.color7:       #a8a19f
*.color15:      #f1efee



URxvt.termName:    rxvt-256color
URxvt.transparent: true
URxvt.shading:     10
URxvt.fading:      15
URxvt.font:        xft:Hack:pixelsize=10, xft:Hack:antialias=false, xft:Hack:antialias=false

URxvt.saveLines:         4096
URxvt.scrollBar:         false
URxvt.scrollTtyOutput:   false
URxvt.scrollWithBuffer:  true
URxvt.scrollTtyKeypress: true
URxvt.urgentOnBell:      true
URxvt.iconFile:          /usr/share/icons/Numix-Circle/48x48/apps/xterm-color_48x48.svg

URxvt.perl-lib:       ~/.config/urxvt
URxvt.perl-ext:       default,cspace,font-size,url-select,tabbedex

URxvt.url-launcher:   /usr/bin/xdg-open

! Tabbedex features
URxvt.tabbed.new-button:       no
URxvt.tabbed.autohide:         yes
URxvt.tabbed.no-tabbedex-keys: yes

! Tabbedex colors
URxvt.tabbed.tabbar-fg:   244
URxvt.tabbed.tabbar-bg:   16
URxvt.tabbed.tab-fg:      255
URxvt.tabbed.tab-bg:      52
URxvt.tabbed.bell-tab-fg: 255
URxvt.tabbed.bell-tab-bg: 160
URxvt.tabbed.bell-fg:     244
URxvt.tabbed.bell-bg:     17
URxvt.tabbed.title-fg:    28
URxvt.tabbed.title-bg:    16

! Tabbedex keybindings (4-1: Super + Alt)
URxvt.keysym.4-1-Down:    perl:tabbedex:new_tab
URxvt.keysym.4-1-Left:    perl:tabbedex:prev_tab
URxvt.keysym.4-1-Right:   perl:tabbedex:next_tab
URxvt.keysym.4-1-Up:      perl:tabbedex:rename_tab
URxvt.keysym.4-1-C-Left:  perl:tabbedex:move_tab_left
URxvt.keysym.4-1-C-Right: perl:tabbedex:move_tab_right

! Font-size (C-1: Ctrl + Alt)
URxvt.keysym.C-1-Up:     perl:font-size:increase
URxvt.keysym.C-1-Down:   perl:font-size:decrease
URxvt.keysym.C-S-1-Up:   perl:font-size:incglobal
URxvt.keysym.C-S-1-Down: perl:font-size:decglobal

! url-select
URxvt.keysym.M-u: perl:url-select:select_next
URxvt.url-select.launcher: /usr/bin/xdg-open
URxvt.url-select.underline: yes

! rofi -- dmenu clone
rofi.opacity:  100
rofi.width:    90
rofi.lines:    25
rofi.font:     Iosevka Medium 10
rofi.location: 0
rofi.padding:  5

rofi.color-enabled: true
rofi.color-window: #3f3f3f, #000000, #000000

! State:           bg,      fg,      bgalt    hlbg,    hlfg
! zenburn:         bg,      fg,      bg-05,   bg+1,    fg+1
rofi.color-normal: #3f3f3f, #dcdccc, #383838, #4f4f4f, #ffffef
!                  blue-4,  fg,      blue-5,  blue-3,  fg+1
rofi.color-active: #4c7073, #dcdccc, #366060, #5c888b, #ffffef
!                  red-4,   fg,      red-5,   red-3,   fg+1
rofi.color-urgent: #8c5353, #dcdccc, #7c4343, #9c6363, #ffffef

!(call-process-shell-command "xrdb -load ~/.Xresources")
```

i have no clue why is not changing rofi color scheme

P.S. does pywal works with polybar, if yes how can i change the color of that too?

**Comment by dylanaraps** [comment] 2017-12-30 20:52
What happens if you remove this line?:

```
!(call-process-shell-command "xrdb -load ~/.Xresources")
```

**Comment by shizonic** [comment] 2017-12-31 10:56
Same issue here... Rofi colors aren't applied with latest release.

**Comment by FreedomSka** [comment] 2017-12-31 12:57
I have removed the color settings of rofi and the line

```!(call-process-shell-command "xrdb -load ~/.Xresources")```

still not working, also i have noticed that after i run wal -i <picture> if i do
``` $ xrdb -query ```
and
``` $ cat ~/.Xresources ```
the output are different

the data from **xrdb -query** contains the new theme scheme from the wallpaper and the **~/.Xresources** have the hold config

**Comment by shizonic** [comment] 2017-12-31 13:34
@FreedomSka Version 0.7.0 works!

**Comment by FreedomSka** [comment] 2017-12-31 13:50
i am using 0.7

**Comment by shizonic** [comment] 2017-12-31 13:53
@FreedomSka Okay, very strange... For me it also does not work except with version 0.7.0...

**Comment by FreedomSka** [comment] 2017-12-31 14:11
i have arch and i have installed the package _pywal_ from **aur** (version 07.0.0-1) and not __pywal-git__ (version 1.09)

**Comment by dylanaraps** [comment] 2017-12-31 20:38
1. If you have a `rofi` config file with color definitions they will overwrite `wal`.
2. Try the latest master version and tell me if it works.
    - See: https://github.com/dylanaraps/pywal/wiki/Installation#manualgit-install
    - Do `wal -c` then `wal -i`

**Comment by i-bsd** [comment] 2017-12-31 20:41
Can confirm that this is indeed not working.

I'm on FreeBSD. pywal no longer changes rofi color scheme.

**Comment by dylanaraps** [comment] 2017-12-31 20:44
Try the latest master @i-bsd

**Comment by i-bsd** [comment] 2017-12-31 20:46
Ok just did.

Now it's not changing rofi, wallpaper or i3bar - just terminal.

**Comment by dylanaraps** [comment] 2017-12-31 20:53
Try the latest commit with `wal -c` then `wal -i /img`. I've figured out what the issue was.

**Comment by i-bsd** [comment] 2017-12-31 20:57
I just did.

With latest commit, pywal isn't working for me (only changes urxvt colors and nothing else).

**Comment by i-bsd** [comment] 2017-12-31 20:58
To be honest, the previous version is preferable. It worked apart from rofi. Now it's broken.

**Comment by dylanaraps** [comment] 2017-12-31 21:13
Look at the diff between versions \[1\], the code related to wallpaper changing, i3 etc hasn't changed at all. The only breaking code change was splitting the `xres` settings into two separate files.

I've figured out why it was broken too. I was using the `#include` directive to include the `rofi` file in the main `xres` file. But as it turns out, for the `#include` feature to work you need to have GNU CPP installed. 

I've since swapped to passing both files to `xrdb` which is effectively a revert of the `rofi` changes in `1.0.0`. The issue should now be fixed. \[2\]

I'm not sure why `pywal` post `0.7.5` isn't working for you but it sounds more like an installation error than anything else. Before you go blaming `pywal` for being broken check that you've installed it correctly.

\[1\] https://github.com/dylanaraps/pywal/compare/0.7.5...master
\[2\] https://github.com/dylanaraps/pywal/commit/e59c7f866e64073a55cfcae893c6f8222911d590

**Comment by dylanaraps** [comment] 2017-12-31 21:21
Try the latest master.

**Comment by i-bsd** [comment] 2017-12-31 21:26
Ok for some reason I needed to restart X to see changes. Rofi is now changing when I run pywal BUT:

https://imgur.com/a/OWnDc

Rofi isn't using the correct color scheme. It's changing each time but seems to be adopting the wrong colors. See the image link above.

I'll try the latest master to see if it makes a difference.

**Comment by i-bsd** [comment] 2017-12-31 21:46
Just tried latest commit.

Rofi is now working properly but i3 (i3bar) is not.

I appreciate your work BTW. Thanks for working to fix this.

**Comment by dylanaraps** [comment] 2017-12-31 21:48
I'll install i3 and see if I can reproduce this.

**Comment by i-bsd** [comment] 2017-12-31 21:52
Thanks. Also URxvt changes are no longer permanent (they change when initially running pywal but if I restart X, they reset). I tried doing a pywal refresh but doesn't do anything.

Rofi and dunst work perfectly now.

i3 - does not change at all.

URxvt - changes once then loses changes when restarting X.

**Comment by shizonic** [comment] 2017-12-31 21:57
@dylanaraps thanks also ! I really appreciate your work. Right now I am not at home but asap I will help to solve the issues....

**Comment by dylanaraps** [comment] 2017-12-31 22:11
Try the latest master again. It turns out that you cant pass multiple files to `xrdb` at once.

**Comment by i-bsd** [comment] 2017-12-31 22:22
Ok it looks like you might have solved it. Everything seems to be running properly.

Hugely appreciated mate.

**Comment by dylanaraps** [comment] 2017-12-31 22:29
Closing this, thanks for testing! I'll push a release now.

**Closed by dylanaraps** 2017-12-31 22:29 UTC
Labels: bug
